definitions:
  tenant.CreateTenantRequest:
    properties:
      document:
        type: string
      name:
        type: string
    required:
    - document
    - name
    type: object
  tenant.TenantResponse:
    properties:
      document:
        type: string
      live:
        type: boolean
      name:
        type: string
      uuid:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/tenant/create:
    post:
      consumes:
      - application/json
      description: Cria um novo tenant no sistema
      parameters:
      - description: Dados do tenant
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/tenant.CreateTenantRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/tenant.TenantResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Cria um novo tenant
      tags:
      - tenant
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
