definitions:
  dto.CreateTenantRequest:
    properties:
      document:
        type: string
      live:
        type: boolean
      name:
        type: string
    required:
    - document
    - live
    - name
    type: object
  dto.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 8
        type: string
      role:
        $ref: '#/definitions/model.UserRole'
    required:
    - email
    - name
    - password
    - role
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.LoginResponse:
    properties:
      expire:
        type: string
      token:
        type: string
      user:
        $ref: '#/definitions/dto.UserResponse'
    type: object
  dto.OTPRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  dto.OTPResetPasswordRequest:
    properties:
      email:
        type: string
      otp:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - otp
    - password
    type: object
  dto.TenantResponse:
    properties:
      createAt:
        type: string
      document:
        type: string
      live:
        type: boolean
      name:
        type: string
      updateAt:
        type: string
      uuid:
        type: string
    type: object
  dto.TenantsResponse:
    properties:
      page:
        type: integer
      size:
        type: integer
      tenants:
        items:
          $ref: '#/definitions/dto.TenantResponse'
        type: array
    type: object
  dto.UpdateTenantRequest:
    properties:
      document:
        type: string
      live:
        type: boolean
      name:
        type: string
    type: object
  dto.UpdateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        $ref: '#/definitions/model.UserRole'
    type: object
  dto.UserListResponse:
    properties:
      users:
        items:
          $ref: '#/definitions/dto.UserResponse'
        type: array
    type: object
  dto.UserResponse:
    properties:
      create_at:
        type: string
      email:
        type: string
      live:
        type: boolean
      name:
        type: string
      role:
        $ref: '#/definitions/model.UserRole'
      tenant_uuid:
        type: string
      update_at:
        type: string
      uuid:
        type: string
    type: object
  model.UserRole:
    enum:
    - SYSTEM_ADMIN
    - TENANT_ADMIN
    - TENANT_USER
    type: string
    x-enum-varnames:
    - RoleSystemAdmin
    - RoleTenantAdmin
    - RoleTenantUser
  rest_err.Causes:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  rest_err.RestErr:
    properties:
      causes:
        items:
          $ref: '#/definitions/rest_err.Causes'
        type: array
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Recebe email e senha, autentica o usuário e retorna o token de
        acesso.
      parameters:
      - description: Credenciais do Usuário (Email e Senha)
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login bem-sucedido
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Requisição inválida (JSON mal formatado)
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: Credenciais inválidas (usuário/senha errados)
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "409":
          description: Token duplicado ou conflito
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Efetua o login do usuário
      tags:
      - Auth
  /api/auth/logout/{token}:
    post:
      consumes:
      - application/json
      description: Invalida o token de acesso atual do usuário.
      parameters:
      - description: Token de acesso a ser revogado
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Token revogado com sucesso
        "404":
          description: Token não encontrado
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Revoga o token de acesso
      tags:
      - Auth
  /api/auth/otp:
    post:
      consumes:
      - application/json
      description: Gera um OTP vinculado ao e-mail e envia por e-mail.
      parameters:
      - description: Email para envio do OTP
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.OTPRequest'
      produces:
      - application/json
      responses:
        "202":
          description: OTP enviado com sucesso
        "400":
          description: JSON inválido
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "409":
          description: OTP já existente
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Solicita um código OTP
      tags:
      - Auth
  /api/auth/password/reset:
    post:
      consumes:
      - application/json
      description: Valida o OTP e troca a senha do usuário.
      parameters:
      - description: Email, OTP e nova senha
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.OTPResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Senha alterada com sucesso
        "400":
          description: JSON inválido
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "403":
          description: OTP inválido
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Troca a senha usando OTP
      tags:
      - Auth
  /api/v1/tenant:
    delete:
      description: Exclui permanentemente um tenant no sistema usando o UUID ou o
        Documento (CNPJ/CPF). Pelo menos um dos dois campos deve ser fornecido.
      parameters:
      - description: 'UUID do tenant a ser excluído. (Ex: 8871abf3-ed11-4770-b986-e8d98d022d4f)'
        in: query
        name: uuid
        type: string
      - description: 'Documento (CNPJ/CPF) do tenant a ser excluído. (Ex: 12345678901234)'
        in: query
        name: document
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Tenant excluído com sucesso (No Content).
          schema:
            type: string
        "400":
          description: Requisição inválida (UUID inválido, ou nenhum dos campos 'uuid'/'document'
            fornecido).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: Tenant não encontrado com os dados fornecidos.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Deleta um Tenant
      tags:
      - Tenant
    get:
      description: Busca um tenant no sistema usando o UUID ou o Documento (CNPJ/CPF).
        Pelo menos um dos dois campos deve ser fornecido.
      parameters:
      - description: 'UUID do tenant a ser buscado. (Ex: 8871abf3-ed11-4770-b986-e8d98d022d4f)'
        in: query
        name: uuid
        type: string
      - description: 'Documento (CNPJ/CPF) do tenant a ser buscado. (Ex: 12345678901234)'
        in: query
        name: document
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Tenant encontrado com sucesso.
          schema:
            $ref: '#/definitions/dto.TenantResponse'
        "400":
          description: Requisição inválida (UUID inválido, ou nenhum dos campos 'uuid'/'document'
            fornecido).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: Tenant não encontrado com os dados fornecidos.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Busca um Tenant
      tags:
      - Tenant
    post:
      consumes:
      - application/json
      description: Registra um novo tenant (empresa/organização) no sistema.
      parameters:
      - description: Objeto do tenant que precisa ser criado.
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTenantRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Tenant criado com sucesso.
          schema:
            $ref: '#/definitions/dto.TenantResponse'
        "400":
          description: Requisição inválida (corpo JSON mal formatado ou dados de entrada
            inválidos).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "409":
          description: Conflito (o 'document' fornecido já está em uso).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Cria um novo Tenant
      tags:
      - Tenant
  /api/v1/tenant/{uuid}:
    patch:
      consumes:
      - application/json
      description: Atualiza dados de um tenant existente. O tenant a ser atualizado
        é identificado pelo UUID no path
      parameters:
      - description: UUID do tenant a ser atualizado.
        in: path
        name: uuid
        required: true
        type: string
      - description: Campos do tenant a serem atualizados. Apenas os campos presentes
          serão modificados.
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateTenantRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Tenant atualizado com sucesso.
          schema:
            $ref: '#/definitions/dto.TenantResponse'
        "400":
          description: Requisição inválida (corpo JSON mal formatado, UUID inválido
            ou dados de entrada inválidos).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: Tenant não encontrado para o UUID fornecido.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "409":
          description: Conflito (o novo 'document' fornecido já está em uso por outro
            tenant).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Atualiza um Tenant
      tags:
      - Tenant
  /api/v1/tenant/list:
    get:
      description: Retorna uma lista paginada de todos os tenants registrados no sistema.
      parameters:
      - default: 1
        description: O número da página a ser retornada (deve ser >= 1).
        in: query
        name: page
        required: true
        type: integer
      - default: 10
        description: O número de itens por página (máximo 100).
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Lista de tenants retornada com sucesso.
          schema:
            $ref: '#/definitions/dto.TenantsResponse'
        "400":
          description: Requisição inválida (parâmetros de paginação ausentes ou inválidos,
            ou pageSize > 100).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Lista Tenants
      tags:
      - Tenant
  /api/v1/user/{identifier}:
    delete:
      description: |-
        Exclui permanentemente um usuário existente do sistema, identificado pelo UUID ou Email.
        Esta operação não é reversível. Se o usuário não existir, retorna erro 404.
      parameters:
      - description: Identificador (UUID ou Email) do usuário a ser removido.
        in: path
        name: identifier
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Usuário removido com sucesso (sem conteúdo no corpo da resposta).
        "400":
          description: Requisição inválida (identificador ausente ou mal formatado).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: Não encontrado (o usuário especificado não existe).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Remove um usuário
      tags:
      - User
    get:
      description: Obtém os detalhes de um usuário específico, buscando pelo UUID
        ou pelo email.
      parameters:
      - description: Identificador (UUID ou Email) do Usuário a ser buscado.
        in: path
        name: identifier
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Usuário encontrado com sucesso.
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Requisição inválida (o 'identifier' do usuário está ausente
            ou é inválido).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: Não encontrado (o recurso solicitado não foi localizado).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "409":
          description: 'Conflito (o serviço retornou um erro de conflito, ex: ''email
            duplicado'').'
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Busca um usuário
      tags:
      - User
    patch:
      consumes:
      - application/json
      description: |-
        Atualiza parcialmente os detalhes de um usuário existente (nome, email, senha ou role).
        Apenas os campos fornecidos no corpo do JSON serão atualizados.
      parameters:
      - description: Identificador (UUID ou Documento) do usuarioa ser atualizado.
        in: path
        name: identifier
        required: true
        type: string
      - description: Campos do usuário que precisam ser atualizados.
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Usuário atualizado com sucesso.
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Requisição inválida (UUID mal formatado, corpo JSON mal formatado
            ou falha na validação).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: Não encontrado (o 'identifier' do usuário não corresponde a
            nenhum usuário existente).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "409":
          description: Conflito (o 'email' fornecido já está em uso por outro usuário).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Atualiza um usuário
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Registra um novo usuário no sistema, associado a um tenant (empresa/organização).
      parameters:
      - description: Identificador (UUID ou Documento) do Tenant ao qual o usuário
          será associado.
        in: path
        name: identifier
        required: true
        type: string
      - description: Objeto do usuário que precisa ser criado.
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Usuário criado com sucesso.
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Requisição inválida (corpo JSON mal formatado, dados de entrada
            inválidos, ou 'identifier' do tenant ausente).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: Tenant não encontrado (o 'identifier' fornecido não corresponde
            a nenhum tenant existente).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "409":
          description: Conflito (o 'email' fornecido já está em uso).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Cria um novo Usuário
      tags:
      - User
  /api/v1/user/list:
    get:
      description: Retorna uma lista paginada de usuários.
      parameters:
      - default: 1
        description: Número da página para paginação.
        in: query
        name: page
        type: integer
      - default: 10
        description: Número de itens por página.
        in: query
        maximum: 100
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Lista de usuários recuperada com sucesso.
          schema:
            $ref: '#/definitions/dto.UserListResponse'
        "400":
          description: Requisição inválida (parâmetros 'page' ou 'size' inválidos,
            ou erro ao listar).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Lista usuários
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
