definitions:
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth.LoginResponse:
    properties:
      expire:
        type: string
      token:
        type: string
      user:
        $ref: '#/definitions/user.UserResponseDto'
    type: object
  auth.OTPRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  auth.OTPResetPasswordRequest:
    properties:
      email:
        type: string
      otp:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - otp
    - password
    type: object
  rest_err.Causes:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  rest_err.RestErr:
    properties:
      causes:
        items:
          $ref: '#/definitions/rest_err.Causes'
        type: array
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
  tenant.CreateTenantRequestDto:
    properties:
      document:
        type: string
      name:
        type: string
    required:
    - document
    - name
    type: object
  tenant.TenantResponseDto:
    properties:
      createAt:
        type: string
      document:
        type: string
      live:
        type: boolean
      name:
        type: string
      updateAt:
        type: string
      uuid:
        type: string
    type: object
  tenant.TenantsResponseDto:
    properties:
      page:
        type: integer
      size:
        type: integer
      tenants:
        items:
          $ref: '#/definitions/tenant.TenantResponseDto'
        type: array
    type: object
  tenant.UpdateTenantRequestDto:
    properties:
      document:
        type: string
      live:
        type: boolean
      name:
        type: string
    type: object
  user.CreateUserRequestDto:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 8
        type: string
      role:
        $ref: '#/definitions/user.UserRole'
    required:
    - email
    - name
    - password
    - role
    type: object
  user.UpdateUserRequestDto:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        $ref: '#/definitions/user.UserRole'
    type: object
  user.UserResponseDto:
    properties:
      create_at:
        type: string
      email:
        type: string
      live:
        type: boolean
      name:
        type: string
      role:
        $ref: '#/definitions/user.UserRole'
      tenant_uuid:
        type: string
      update_at:
        type: string
      uuid:
        type: string
    type: object
  user.UserRole:
    enum:
    - SYSTEM_ADMIN
    - TENANT_ADMIN
    - TENANT_USER
    - SYSTEM_ADMIN
    - TENANT_ADMIN
    - TENANT_USER
    type: string
    x-enum-varnames:
    - RoleSystemAdmin
    - RoleTenantAdmin
    - RoleTenantUser
info:
  contact: {}
paths:
  /api/auth/healthcheck:
    get:
      consumes:
      - application/json
      description: Retorna os dados do usuário logado se o token for válido.
      produces:
      - application/json
      responses:
        "200":
          description: Dados do usuário logado
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "401":
          description: Não autorizado
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Verifica o status do login
      tags:
      - Auth
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Recebe email e senha, autentica o usuário e retorna o token de
        acesso.
      parameters:
      - description: Credenciais do Usuário (Email e Senha)
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login bem-sucedido
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Requisição inválida (JSON mal formatado)
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: Credenciais inválidas (usuário/senha errados)
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "409":
          description: Token duplicado ou conflito
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Efetua o login do usuário
      tags:
      - Auth
  /api/auth/logout/{token}:
    post:
      consumes:
      - application/json
      description: Invalida o token de acesso atual do usuário.
      parameters:
      - description: Token de acesso a ser revogado
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Token revogado com sucesso
        "404":
          description: Token não encontrado
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Revoga o token de acesso
      tags:
      - Auth
  /api/auth/otp:
    post:
      consumes:
      - application/json
      description: Gera um OTP vinculado ao e-mail e envia por e-mail.
      parameters:
      - description: Email para envio do OTP
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.OTPRequest'
      produces:
      - application/json
      responses:
        "202":
          description: OTP enviado com sucesso
        "400":
          description: JSON inválido
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "409":
          description: OTP já existente
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Solicita um código OTP
      tags:
      - Auth
  /api/auth/password/reset:
    post:
      consumes:
      - application/json
      description: Valida o OTP e troca a senha do usuário.
      parameters:
      - description: Email, OTP e nova senha
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.OTPResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Senha alterada com sucesso
        "400":
          description: JSON inválido
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "403":
          description: OTP inválido
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Troca a senha usando OTP
      tags:
      - Auth
  /api/tenant:
    delete:
      description: Exclui permanentemente um tenant no sistema usando o UUID ou o
        Documento (CNPJ/CPF). Pelo menos um dos dois campos deve ser fornecido.
      parameters:
      - description: 'UUID do tenant a ser excluído. (Ex: 8871abf3-ed11-4770-b986-e8d98d022d4f)'
        in: query
        name: uuid
        type: string
      - description: 'Documento (CNPJ/CPF) do tenant a ser excluído. (Ex: 12345678901234)'
        in: query
        name: document
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: model.Tenant excluído com sucesso (No Content).
          schema:
            type: string
        "400":
          description: Requisição inválida (UUID inválido, ou nenhum dos campos 'uuid'/'document'
            fornecido).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: model.Tenant não encontrado com os dados fornecidos.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Deleta um model.Tenant
      tags:
      - Tenant
    get:
      description: Busca um tenant no sistema usando o UUID ou o Documento (CNPJ/CPF).
        Pelo menos um dos dois campos deve ser fornecido.
      parameters:
      - description: 'UUID do tenant a ser buscado. (Ex: 8871abf3-ed11-4770-b986-e8d98d022d4f)'
        in: query
        name: uuid
        type: string
      - description: 'Documento (CNPJ/CPF) do tenant a ser buscado. (Ex: 12345678901234)'
        in: query
        name: document
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: model.Tenant encontrado com sucesso.
          schema:
            $ref: '#/definitions/tenant.TenantResponseDto'
        "400":
          description: Requisição inválida (UUID inválido, ou nenhum dos campos 'uuid'/'document'
            fornecido).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: model.Tenant não encontrado com os dados fornecidos.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Busca um Tenant
      tags:
      - Tenant
  /api/tenant/{uuid}:
    patch:
      consumes:
      - application/json
      description: Atualiza dados de um tenant existente. O tenant a ser atualizado
        é identificado pelo UUID no path
      parameters:
      - description: UUID do tenant a ser atualizado.
        in: path
        name: uuid
        required: true
        type: string
      - description: Campos do tenant a serem atualizados. Apenas os campos presentes
          serão modificados.
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/tenant.UpdateTenantRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: model.Tenant atualizado com sucesso.
          schema:
            $ref: '#/definitions/tenant.TenantResponseDto'
        "400":
          description: Requisição inválida (corpo JSON mal formatado, UUID inválido
            ou dados de entrada inválidos).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: model.Tenant não encontrado para o UUID fornecido.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "409":
          description: Conflito (o novo 'document' fornecido já está em uso por outro
            tenant).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Atualiza um Tenant
      tags:
      - Tenant
  /api/tenant/create:
    post:
      consumes:
      - application/json
      description: Cria um novo tenant no sistema
      parameters:
      - description: Dados do tenant
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/tenant.CreateTenantRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/tenant.TenantResponseDto'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Cria um novo tenant
      tags:
      - Tenant
  /api/tenant/list:
    get:
      description: Retorna uma lista paginada de todos os tenants registrados no sistema.
      parameters:
      - default: 1
        description: O número da página a ser retornada (deve ser >= 1).
        in: query
        name: page
        required: true
        type: integer
      - default: 10
        description: O número de itens por página (máximo 100).
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Lista de tenants retornada com sucesso.
          schema:
            $ref: '#/definitions/tenant.TenantsResponseDto'
        "400":
          description: Requisição inválida (parâmetros de paginação ausentes ou inválidos,
            ou pageSize > 100).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Lista Tenants
      tags:
      - Tenant
  /api/user/{identifier}:
    delete:
      description: Exclui permanentemente um usuário no sistema usando o UUID ou o
        Email passado na URL.
      parameters:
      - description: UUID ou Email do usuário a ser deletado
        in: path
        name: identifier
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Deleta um Usuário
      tags:
      - User
    get:
      description: Busca um usuário. Se o identificador for passado na URL, busca
        aquele usuário específico. Se for vazio (/api/user), busca o perfil do usuário
        logado.
      parameters:
      - description: UUID ou Email do usuário (Opcional)
        in: path
        name: identifier
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserResponseDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Busca um Usuário
      tags:
      - User
    patch:
      consumes:
      - application/json
      description: Atualiza dados de um usuário existente. O usuário a ser atualizado
        é identificado pelo UUID/Email no path.
      parameters:
      - description: Idenficador do usuário
        in: path
        name: identifier
        required: true
        type: string
      - description: Dados para atualização
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.UpdateUserRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserResponseDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Atualiza um Usuário
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Registra um novo usuário no sistema, associado a um tenant (empresa/organização).
      parameters:
      - description: Identificador (UUID ou Documento) do Tenant ao qual o usuário
          será associado.
        in: path
        name: identifier
        required: true
        type: string
      - description: Objeto do usuário que precisa ser criado.
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Usuário criado com sucesso.
          schema:
            $ref: '#/definitions/user.UserResponseDto'
        "400":
          description: Requisição inválida (corpo JSON mal formatado, dados de entrada
            inválidos, ou 'identifier' do tenant ausente).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "404":
          description: Tenant não encontrado (o 'identifier' fornecido não corresponde
            a nenhum tenant existente).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "409":
          description: Conflito (o 'email' fornecido já está em uso).
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Erro interno do servidor.
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Cria um novo Usuário
      tags:
      - User
  /api/user/list:
    get:
      description: Retorna uma lista paginada de usuários.
      parameters:
      - description: Número da página (padrão 1)
        in: query
        name: page
        type: integer
      - description: Tamanho da página (padrão 10)
        in: query
        name: size
        type: integer
      - description: 'Filtro opcional: UUID ou Documento do Tenant (Apenas para SystemAdmin)'
        in: query
        name: tenant_identifier
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.UserResponseDto'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      security:
      - BearerAuth: []
      summary: Lista Usuários
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
